### ISSUE TITLE
Update copy on registration email

### ISSUE THREAD

**Issue by macep** [macep/makeries-api-v2#19]
![image](https://user-images.githubusercontent.com/3285925/52526274-2482e300-2cae-11e9-997f-0d8df5624a3f.png)

Top Line: 
Verify your Just Got Made Account

- Can we change the banner ‘artwork’? i.e. brand colours and JGM logo instead of the tick in circle? 

- can we change the reply-to email address to info@justgotmade.com
- subject line: Verify your Just Got Made Account 
- design is very techy again! How much control do we have over this? 
-  Sentence : "If you are having any issues with your account, please don't hesitate to contact us by replying to this mail."  
-  Sentence: "You’re receiving this email because you have an account in Just Got Made. If you are not sure why you’re receiving this, please contact us through our Support Center.
Please reword to contact at email info@Justgotmade.com for now. 
 
- The Verify your account button should link to the directory, not the JGM homepage. i.e. /directory.

**Comment by Cristialt** [comment]
we don't have control over this section for the moment as I told you in the beginning
we need to setup a complete production env and then we will be able to setup these things for production only; testing si using this limited version...

**Comment by macep** [comment]
Approx how much time, money will that cost?

Pete
07971 686 363
