### ISSUE TITLE
remove the word "Error" from the password reset page

### ISSUE THREAD

**Issue by macep** [macep/makeries-api-v2#25]
When you submit your email for a password reset you see the following message, please can you remove the word "Error" as this isn't an error is just a helpful message!
<img width="438" alt="image" src="https://user-images.githubusercontent.com/3285925/53492648-48f20400-3a91-11e9-80ca-15c9e4868a13.png">

**Comment by macep** [comment]
Also, when I reset my password, I didn't reset the password reset email!

**Comment by Cristialt** [comment]
![Screenshot 2019-03-12 at 11 22 21 PM](https://user-images.githubusercontent.com/5858729/54237026-b71cd900-451d-11e9-9a29-3177566c31c3.png)
