### ISSUE TITLE
Update the Testimonial text so it is not justified and each line appears on a new line

### ISSUE THREAD

**Issue by macep** [macep/makeries-api-v2#29]
On the maker detail page
<img width="769" alt="image" src="https://user-images.githubusercontent.com/3285925/53730780-ce4e2d80-3e70-11e9-82d8-e48a2ec75e05.png">
Update the Testimonial text so it is not justified and each new line entered in the DB appears on a new line. The above should be two lines:
These guys are the greatest! - Pete
Epic epic epic - Paul
If you could alternate them so the first is left aligned, the next right aligned and so on that would be even better
These guys are the greatest! - Pete
Epic epic epic - Paul

**Comment by Cristialt** [comment]
I did a quick update, removing `align justify` but we'll resolve this kind of things better

**Comment by macep** [comment]
Can you also display so that each newline set in the DB displays as a new line on the webpage
