### ISSUE TITLE
Load Next Page and Load All links are hanging when clicked on the on the All Suppliers view

### ISSUE THREAD

**Issue by macep** [macep/makeries-api-v2#32]
Load Next Page and Load All seem to be not working - I get the spinning JGM icon and nothing ever loads. The user is unable to cancel/ click on any links unless I shift+reload the whole page

**Comment by Cristialt** [comment]
I don't see this, but tell me how to reproduce, maybe it's a bug...

**Comment by macep** [comment]
Might be fixed by the apache restart - I’ll see if I can reproduce

Pete
07971 686 363
