### ISSUE TITLE
List of Featured Suppliers not correct on the Featured Suppliers page

### ISSUE THREAD

**Issue by macep** [macep/makeries-api-v2#38]
Hi Cristi, I updated a couple of makers in the database (setting the featured flag to yes) but they're not appearing on the "Featured Suppliers" page of the directory. Is there something going on with the caching such that it's not being updated?

Example: Featured Suppliers appear here: http://directory.justgotmade.com

But I've updated this maker http://admin.makeries.com/maker/edit/?id=119 (set featured to true) and it's not appearing on the Featured Suppliers page

**Comment by Cristialt** [comment]
Yes, it's a caching issue; it'll be in the ui automatically after 24h, and we have to change that to something like 4h maybe 

anyway, 
for the admins we will also introduce a 'force refresh' hidden button as well

**Comment by macep** [comment]
There are still too many suppliers appearing in the Featured menu, I checked one currently showing on the page (London Button Company) - it does not have the Featured flag set when I check it in the admin screens:

<img width="1120" alt="image" src="https://user-images.githubusercontent.com/3285925/81804856-c2003e80-9511-11ea-86ee-2286b00f07a3.png">

<img width="491" alt="image" src="https://user-images.githubusercontent.com/3285925/81804915-de9c7680-9511-11ea-86ac-8fbcb737e723.png">

**Comment by macep** [comment]
This is still an issue! I  I noticed also that the heading of the page (see in browser tab) says "Search All 283 Suppliers". Checked the first supplier in the list (Jenkip) and they don't have the featured flag set either

<img width="699" alt="image" src="https://user-images.githubusercontent.com/3285925/82367717-29cff100-9a0c-11ea-8c60-6116bc21b1d8.png">

**Comment by macep** [comment]
Tested fixed
