### ISSUE TITLE
Only makers that are marked as published should be visible in the front end

### ISSUE THREAD

**Issue by macep** [macep/makeries-api-v2#58]
This is so we can keep some suppliers inactive until they are ready to be viewed.

I think we had this feature but it may have got lost somewhere along the way

**Comment by macep** [comment]
This code is ready to turn on, just need to go through existing makers and ensure they've got the flag set

**Comment by Cristialt** [comment]
ok, let me know _when_

**Comment by macep** [comment]
In the maker admin screen there is a field called "Contact Name" This is the field that should be used as contact name.
If there is nothing in the contact name field then nothing (including "Contact Name:" should be displayed
