### ISSUE TITLE
Question: Is it possible to see which profiles have a particular taxonomy set

### ISSUE THREAD

**Issue by macep** [macep/makeries-api-v2#59]
When you view the services or products in the admin screen is there a way we can see everyone who has this service assigned. At the moment I have to go into each individual profile one by one and scroll down to see what's been assigned.
 For each service listed here
http://admin.makeries.com/service/index/?&pageNr=1&sort_by=name
I can go to a specific service, e.g. Fabrication
http://admin.makeries.com/service/edit/?id=7
But I can't see everyone who has this service in one place

What's the easiest/ quickest way to see everyone who has this? Do i have to go to the API and make an API request directly or can it be easily displayed on the service admin page. i.e. underneath the box where you can edit the name:
http://admin.makeries.com/service/edit/?id=7

**Comment by macep** [comment]
Presume I should just do a select in the database directly? Can you let me know the name/ login details for the database and how I can access it directly

**Comment by Cristialt** [comment]
You're having a REST interface in front so no direct DB queries.
Therefore we can add a filter on the search endpoint where you can achieve such
