### ISSUE TITLE
Updated list of services not selectable (visible) for each maker profile (admin screens)

### ISSUE THREAD

**Issue by macep** [macep/makeries-api-v2#61]
I added a new service called "Biomaterials Upcycling and Reuse":
<img width="569" alt="image" src="https://user-images.githubusercontent.com/3285925/83614952-d3bb8b80-a57d-11ea-9179-4b890ed1ae87.png">

But when I try and select it for the maker it doesn't appear in the list, in fact i don't think the list on the maker profile page accurately reflects the current list of active services at all as I have updated and changed names of some of them since we first imported the data.

<img width="356" alt="image" src="https://user-images.githubusercontent.com/3285925/83615208-2432e900-a57e-11ea-998d-c75fad812631.png">

**Comment by macep** [comment]
I think you've fixed this now?! They list seems to have updated with the correct fields/

**Comment by Cristialt** [comment]
yes
