### ISSUE TITLE
Featured Profiles and Recent Profiles should be different

### ISSUE THREAD

**Issue by macep** [macep/makeries-api-v2#62]
Featured Profiles appear to be the same Profiles when viewed on the You Might Like screen
There is a subtle difference: 

Featured Profiles are the most recent 6 which have the Featured flag set.
Recent are the just the 6 most recently added (i.e they don't need to have the flag set, just the most recently added)

Note that in both cases 6 profiles should be displayed, multiples of 3 look better on the page

**Comment by Cristialt** [comment]
here we have to just change the filter, I have used something for the demo, forgot to replace in the end
