### ISSUE TITLE
Cannot reset auth0 user password for access to admin screens

### ISSUE THREAD

**Issue by macep** [macep/makeries-api-v2#67]
Hi

I just tried resetting the password in Auth0/ User and Roles/ username / Reset Password and I get the following error, am I doing something wrong?
<img width="645" alt="image" src="https://user-images.githubusercontent.com/3285925/84901640-adc8d780-b0a3-11ea-9aa4-7e013b44edba.png">

This is the user:
<img width="887" alt="image" src="https://user-images.githubusercontent.com/3285925/84901769-d781fe80-b0a3-11ea-9010-99033c97c27e.png">

**Comment by Cristialt** [comment]
@macep could be that your user is not allowed to do it
I need the credentials to get in there
everything should work though

**Comment by Cristialt** [comment]
not a bug
